x=input("Enter your name : ")
print(x)
print("WELCOME TO THE CALCULATOR")
a=int(input("Enter first number : "))
b=int(input("Enter second number : "))
print(a+b)
print(a*b)
print(a-b)
print(a/b)
